name: divelog2
description: "A mobile app for divers to log their dive sessions."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  cloud_firestore: ^6.1.1
  drift: ^2.30.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sqlite3_flutter_libs: ^0.5.41

  sqlite3: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
